//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.r_eg.vsSBE.xshd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XshdResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XshdResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.r_eg.vsSBE.xshd.XshdResource", typeof(XshdResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;&quot; extensions=&quot;.js&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;Components&quot; foreground=&quot;DarkCyan&quot; exampleText=&quot;#[Build &quot; /&gt;
        ///    &lt;Color name=&quot;Punctuation&quot; foreground=&quot;DarkSlateGray&quot; /&gt;
        ///    &lt;Color name=&quot;MSBuildPunctuation&quot; foreground=&quot;Indigo&quot; /&gt;
        ///	&lt;Color name=&quot;Digits&quot; foreground=&quot;DarkBlue&quot; /&gt;
        ///	&lt;Color name=&quot;String&quot; foreground=&quot;Sienna&quot; /&gt;
        ///	&lt;Color name=&quot;Literals&quot; foreground=&quot;Blue&quot; /&gt;
        ///    
        ///	&lt;RuleSet ignoreCase=&quot;false&quot;&gt;  
        ///    
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilesMode {
            get {
                return ResourceManager.GetString("FilesMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;&quot; extensions=&quot;.js&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;Components&quot; foreground=&quot;DarkCyan&quot; exampleText=&quot;#[Build &quot; /&gt;
        ///    &lt;Color name=&quot;Punctuation&quot; foreground=&quot;DarkSlateGray&quot; /&gt;
        ///    &lt;Color name=&quot;MSBuildPunctuation&quot; foreground=&quot;Indigo&quot; /&gt;
        ///	&lt;Color name=&quot;Digits&quot; foreground=&quot;DarkBlue&quot; /&gt;
        ///	&lt;Color name=&quot;String&quot; foreground=&quot;Sienna&quot; /&gt;
        ///	&lt;Color name=&quot;Literals&quot; foreground=&quot;Blue&quot; /&gt;
        ///    
        ///	&lt;RuleSet ignoreCase=&quot;false&quot;&gt;  
        ///    
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InterpreterMode {
            get {
                return ResourceManager.GetString("InterpreterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;&quot; extensions=&quot;.js&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;Components&quot; foreground=&quot;DarkCyan&quot; exampleText=&quot;#[Build &quot; /&gt;
        ///    &lt;Color name=&quot;Punctuation&quot; foreground=&quot;DarkSlateGray&quot; /&gt;
        ///    &lt;Color name=&quot;MSBuildPunctuation&quot; foreground=&quot;Indigo&quot; /&gt;
        ///	&lt;Color name=&quot;Digits&quot; foreground=&quot;DarkBlue&quot; /&gt;
        ///	&lt;Color name=&quot;String&quot; foreground=&quot;Sienna&quot; /&gt;
        ///	&lt;Color name=&quot;Literals&quot; foreground=&quot;Blue&quot; /&gt;
        ///    
        ///	&lt;RuleSet ignoreCase=&quot;false&quot;&gt;  
        ///    
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OperationMode {
            get {
                return ResourceManager.GetString("OperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;&quot; extensions=&quot;.js&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///    &lt;Color name=&quot;Components&quot; foreground=&quot;DarkCyan&quot; exampleText=&quot;#[Build &quot; /&gt;
        ///    &lt;Color name=&quot;Punctuation&quot; foreground=&quot;DarkSlateGray&quot; /&gt;
        ///    &lt;Color name=&quot;MSBuildPunctuation&quot; foreground=&quot;Indigo&quot; /&gt;
        ///	&lt;Color name=&quot;Digits&quot; foreground=&quot;DarkBlue&quot; /&gt;
        ///	&lt;Color name=&quot;String&quot; foreground=&quot;Sienna&quot; /&gt;
        ///	&lt;Color name=&quot;Literals&quot; foreground=&quot;Blue&quot; /&gt;
        ///    
        ///	&lt;RuleSet ignoreCase=&quot;false&quot;&gt;  
        ///    
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SBEScripts {
            get {
                return ResourceManager.GetString("SBEScripts", resourceCulture);
            }
        }
    }
}
