// This code was generated by a tool. 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
namespace net.r_eg.vsSBE%namespace%
{
    internal class Version
    {
        public static readonly System.Version number    = new System.Version(%Version%);
        public const string numberWithRevString         = "%VersionRevString%";
        public const string numberString                = "%VersionString%";
        public const string branchName                  = "%branchName%";
        public const string branchSha1                  = "%branchSha1%";
        public const string branchRevCount              = "%branchRevCount%";
    }
}