/* 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Copyright (c) 2013-2014 Developed by reg [Denis Kuzmin] <entry.reg@gmail.com>
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. 
*/

namespace net.r_eg.vsSBE.SBEScripts
{
    public struct TUserVariable
    {
        /// <summary>
        /// Contains the evaluated data or escaped variable/property (without escape symbol)
        /// Using from current the unevaluated field
        /// </summary>
        public string evaluated;

        /// <summary>
        /// Contains the unevaluated mixed data
        /// May contain the another user-variable etc.
        /// </summary>
        public string unevaluated;

        /// <summary>
        /// Used name for this User-Variable
        /// </summary>
        //public string name;

        /// <summary>
        /// Specific project where use this variable.
        /// null value - project by default
        /// </summary>
        //public string project;

        /// <summary>
        /// Storing in the projects files ~ .csproj, .vcxproj, .. 
        /// or with the external containers
        /// </summary>
        /// <remarks>reserved</remarks>
        public bool isPersistence;
    }
}
