/* 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Copyright (c) 2013-2014 Developed by reg [Denis Kuzmin] <entry.reg@gmail.com>
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. 
*/

using System.Collections.Generic;

namespace net.r_eg.vsSBE
{
    public interface IEnvironment
    {
        /// <summary>
        /// Provides projects from EnvDTE
        /// </summary>
        IEnumerable<EnvDTE.Project> DTEProjects { get; }

        /// <summary>
        /// Simple list of names from EnvDTE projects
        /// </summary>
        List<string> DTEProjectsList { get; }

        /// <summary>
        /// Should provide the Build.Evaluation.Project by project name
        /// </summary>
        Microsoft.Build.Evaluation.Project getProject(string project);

        /// <summary>
        /// Should provide active configuration for current solution
        /// </summary>
        EnvDTE80.SolutionConfiguration2 SolutionActiveConfiguration { get; }

        /// <summary>
        /// Should provide all configurations for current solution
        /// </summary>
        IEnumerable<EnvDTE80.SolutionConfiguration2> SolutionConfigurations { get; }

        /// <summary>
        /// Name from "Set as SturtUp Project"
        /// </summary>
        string StartupProjectString { get; }

        /// <summary>
        /// Provide global property for all existing projects
        /// </summary>
        /// <param name="name">Property name</param>
        string getSolutionGlobalProperty(string name);

        /// <summary>
        /// DTE context
        /// </summary>
        EnvDTE80.DTE2 DTE2 { get; }
    }
}
