/* 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Copyright (c) 2013-2014 Developed by reg <entry.reg@gmail.com>
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace net.r_eg.vsSBE
{
    public interface ISBEParser
    {
        /// <summary>
        /// Handler of variables/properties
        /// </summary>
        /// <param name="data">string with $(ident) data</param>
        /// <returns>All evaluated values for data</returns>
        string parseVariablesMSBuild(string data);

        /// <summary>
        /// Handler of SBE-variables for internal processing
        /// </summary>
        /// <param name="raw"></param>
        /// <param name="ident">Expected variable</param>
        /// <param name="vTrue">Value if found</param>
        /// <returns>String with evaluated data as vTrue value or unevaluated as is</returns>
        string parseVariablesSBE(string raw, string ident, string vTrue);

        /// <summary>
        /// Should evaluating property-data
        /// </summary>
        /// <param name="unevaluated">raw unevaluated data</param>
        /// <param name="projectName">Specific project for evaluating</param>
        /// <returns>Evaluated end value</returns>
        string evaluateVariable(string unevaluated, string projectName);
    }
}
