/* 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Copyright (c) 2013 Developed by reg <entry.reg@gmail.com>
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using EnvDTE;
using EnvDTE80;

namespace net.r_eg.vsSBE
{
    public interface IListenerOWPL
    {
        /// <summary>
        /// raw data
        /// e.g. Formatting the Output of a Custom Build Step or Build Event:
        /// http://msdn.microsoft.com/en-us/library/yxkt8b26%28v=vs.100%29.aspx
        /// </summary>
        /// <param name="data"></param>
        void raw(string data);
    }

    /// <summary>
    /// Working with the OutputWindowsPane
    /// Must receive and send different data for own subscribers
    /// </summary>
    internal class OutputWPListener: SynchSubscribers<IListenerOWPL>
    {
        /// <summary>
        /// Keep events for the any pane
        /// </summary>
        private OutputWindowEvents _evtOWP;

        /// <summary>
        /// previous count of lines for EditPoint::GetLines
        /// </summary>
        private int _prevCountLines = 1;

        /// <summary>
        /// events handlers
        /// </summary>
        private _dispOutputWindowEvents_PaneUpdatedEventHandler _ePUpdated;
        private _dispOutputWindowEvents_PaneAddedEventHandler _ePAdded;
        private _dispOutputWindowEvents_PaneClearingEventHandler _ePClearing;

        private Object _eLock = new Object();

        public OutputWPListener(DTE2 dte, string pName)
        {
            _evtOWP     = dte.Events.get_OutputWindowEvents(pName);
            _ePUpdated  = new _dispOutputWindowEvents_PaneUpdatedEventHandler(evtPaneUpdated);
            _ePAdded    = new _dispOutputWindowEvents_PaneAddedEventHandler(evtPaneAdded);
            _ePClearing = new _dispOutputWindowEvents_PaneClearingEventHandler(evtPaneClearing);
        }

        public void attachEvents()
        {
            lock(_eLock) {
                detachEvents();
                _evtOWP.PaneUpdated     += _ePUpdated;
                _evtOWP.PaneAdded       += _ePAdded;
                _evtOWP.PaneClearing    += _ePClearing;
            }
        }

        public void detachEvents()
        {
            lock(_eLock) {
                _evtOWP.PaneUpdated     -= _ePUpdated;
                _evtOWP.PaneAdded       -= _ePAdded;
                _evtOWP.PaneClearing    -= _ePClearing;
            }
        }

        /// <summary>
        /// all collection must receive the raw-data
        /// </summary>
        /// <param name="data">raw data</param>
        protected void notifyRaw(ref string data)
        {
            lock(_eLock) {
                foreach(IListenerOWPL l in subscribers) {
                    l.raw(data);
                }
            }
        }

        protected void evtPaneUpdated(OutputWindowPane pane)
        {
            TextDocument textD   = pane.TextDocument;
            int countLines       = textD.EndPoint.Line;

            if(countLines < 1 || countLines - _prevCountLines < 1) {
                return;
            }

            EditPoint point = textD.StartPoint.CreateEditPoint();

            // text between Start (inclusive) and ExclusiveEnd (exclusive)
            string text = point.GetLines(_prevCountLines, countLines); // e.g. first line: 1, 2
            _prevCountLines = countLines;

            notifyRaw(ref text);
        }

        protected void evtPaneAdded(OutputWindowPane pane)
        {
            _prevCountLines = 1;
        }

        protected void evtPaneClearing(OutputWindowPane pane)
        {
            _prevCountLines = 1;
        }

    }
}
