/* 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Copyright (c) 2013-2014 Developed by reg [Denis Kuzmin] <entry.reg@gmail.com>
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. 
*/

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using net.r_eg.vsSBE.Actions;
using net.r_eg.vsSBE.Exceptions;
using net.r_eg.vsSBE.SBEScripts.Exceptions;

namespace net.r_eg.vsSBE.SBEScripts.Components
{
    public class BuildComponent: IComponent
    {
        /// <summary>
        /// Type of implementation
        /// </summary>
        public ComponentType Type
        {
            get { return ComponentType.Build; }
        }

        /// <summary>
        /// Work with DTE-Commands
        /// </summary>
        protected DTEOperation DTEO
        {
            get {
                if(dteo == null) {
                    Debug.Assert(env != null);
                    dteo = new DTEOperation((EnvDTE.DTE)env.DTE2, Events.SolutionEventType.General);
                }
                return dteo;
            }
        }
        protected DTEOperation dteo;

        /// <summary>
        /// Provides operation with environment
        /// </summary>
        protected IEnvironment env;

        /// <param name="env">Used environment</param>
        public BuildComponent(IEnvironment env)
        {
            this.env = env;
        }

        /// <summary>
        /// Handling with current type
        /// </summary>
        /// <param name="data">mixed data</param>
        /// <returns>prepared and evaluated data</returns>
        public string parse(string data)
        {
            Match m = Regex.Match(data, @"^\[Build
                                              \s+
                                              (                  #1 - full ident
                                                ([A-Za-z_0-9]+)  #2 - subtype
                                                .*
                                              )
                                           \]$", 
                                           RegexOptions.IgnorePatternWhitespace);

            if(!m.Success) {
                throw new SyntaxIncorrectException("Failed BuildComponent - '{0}'", data);
            }
            string ident    = m.Groups[1].Value;
            string subtype  = m.Groups[2].Value;

            switch(subtype) {
                case "cancel": {
                    Log.nlog.Debug("BuildComponent: use stCancel");
                    return stCancel(ident);
                }
            }
            throw new SubtypeNotFoundException("BuildComponent: not found subtype - '{0}'", subtype);
        }

        /// <summary>
        /// The Cancel operation
        /// e.g.: #[Build cancel = true]
        /// </summary>
        /// <param name="data"></param>
        /// <returns>found command</returns>
        protected string stCancel(string data)
        {
            Match m = Regex.Match(data, @"cancel\s*=\s*(false|true|1|0)", RegexOptions.IgnoreCase);
            if(!m.Success) {
                throw new OperandNotFoundException("Failed stCancel - '{0}'", data);
            }

            string val = m.Groups[1].Value.Trim().ToLower();
            switch(val) {
                case "1":
                case "true": {
                    Log.nlog.Debug("stCancel: value is true");
                    DTEO.exec(new string[] { "Build.Cancel" }, false);
                    break;
                }
                case "0":
                case "false": {
                    Log.nlog.Debug("stCancel: value is false");
                    //ignore
                    break;
                }
                default: {
                    throw new IncorrectSyntaxException("stCancel: incorrect value - '{0}'", val);
                }
            }
            Log.nlog.Debug("stCancel: pushed '{0}'", val);
            return String.Empty;
        }
    }
}
