/* 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Copyright (c) 2013-2014 Developed by reg <entry.reg@gmail.com>
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE. 
*/

namespace net.r_eg.vsSBE.Events
{
    /// <summary>
    /// Main container of the Solution Events
    /// </summary>
    public interface ISolutionEvent
    {
        /// <summary>
        /// Status of activation
        /// </summary>
        bool Enabled { get; set; }

        /// <summary>
        /// Optional, unique name for manually identification
        /// </summary>
        string Name { get; set; }

        /// <summary>
        /// Short header about this
        /// </summary>
        string Caption { get; set; }

        /// <summary>
        /// Support of MSBuild environment variables (properties)
        /// </summary>
        bool SupportMSBuild { get; set; }

        /// <summary>
        /// Support of SBE-Scripts
        /// </summary>
        bool SupportSBEScripts { get; set; }

        /// <summary>
        /// Ignore all actions if the build failed
        /// </summary>
        bool IgnoreIfBuildFailed { get; set; }

        /// <summary>
        /// Run only for a specific configuration of solution
        /// strings format as:
        ///   'configname'|'platformname'
        ///   Compatible with: http://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivscfg.get_displayname.aspx
        /// </summary>
        string[] ToConfiguration { get; set; }

        /// <summary>
        /// Run for selected projects with the Execution-Order
        /// </summary>
        IExecutionOrder[] ExecutionOrder { get; set; }

        /// <summary>
        /// Handling process
        /// </summary>
        IEventProcess Process { get; set; }

        /// <summary>
        /// Processing mode
        /// </summary>
        IMode Mode { get; set; }
    }

    /// <summary>
    /// Type of available processing modes
    /// </summary>
    public enum ModeType
    {
        /// <summary>
        /// external commands
        /// </summary>
        File,
        /// <summary>
        /// command script
        /// </summary>
        Interpreter,
        /// <summary>
        /// DTE commands
        /// </summary>
        Operation,
    }
}
